namespace Rewired
{
	[CustomObfuscation(rename = false)]
	internal enum InputPlatform
	{
		CCZTuwVJranWzEkxzHtKCBLLDDz = 0,
		VJDsrfiTpGRdzQKJnkPsFSIDvJQ = 1,
		noJaFmPBaDlcmJbgEsFAjhnvyrY = 2,
		tfuVNjikIuXZCotRWtpoXiXFFjy = 3,
		khvacZlMeuFDIgGxKNYFjbQiePT = 4,
		abUNpVLemVzQdiPJUbUmcLkEnPS = 5,
		UAFYLxwRKGwdDuzEqiTLzFxdNDp = 6,
		xMldJuTPoYllDZMujjoqPQxJvdq = 7,
		gLuYTzVORhznhUEQtzKAZPAPukb = 8,
		zzdlQEmHosuaojNnlyvzuAUPLtW = 9,
		vFUzgFxXICKbWujuKnvIMowmNVZ = 10,
		SbjIIjokQwunFkWvFxPnTEcwbpz = 11,
		XfMMmeGBAOzfqGkeHQPmERGlSU = 12,
		IhAivyuXrqttfLkAleryFACCDdBx = 13,
		djsdTMhOzgTILHForqpCfMafRpov = 14,
		GJLvZBHUgNnpwTpYaOfwAbvXQGg = 15,
		PrVRcZAZmteWSZdbgDXOxafgyki = 16,
		MfajSSDeSGwgDHzQcOQsnYIodRjw = 17,
		sfQfTHaEsGVTzknfyrGkkFSWUtHt = 18,
		xEybPNmsSONEVHMrRfEjcUWFpLM = 19,
		WBJMnSQMqfOiGWhGDfTPDpKDyqqg = 20,
		aYNccUUcSORdQcscpJEBhQJTtmF = 21,
		QIGaKagwdRGRqqXLyHmYTOlrKvUS = 22,
		xscorYnqrkpFTxvoOHIWVBlOJly = 23,
		gQnMHSxAOXFsFFdxhmLXahujxbaG = 24,
		qaThbhiDqukPyuOMNSJlGvuqLEwD = 25,
		kVnJTNbRYkvodfAKMBmMEfHuOAd = 26,
		bxaasTdMznBjRfXVzcPIGJQPgSJ = 27,
		elLfMGydyWvZuItGkKpfXEMHGQx = 28,
		iWbnOlRhMMVmWixGaGdAcDeNfhsG = 29,
		ztLcTzaATkNCzNXgSvmvwhMRNoDG = 30,
		UcUpzCVvFrWiNUdoAxJgFpSsIcB = 31,
		kMscIdWCQBuelqSOQmMQTznFduA = 32,
		yXXHOaiicJTynIXzBMlJCijyKku = 33,
		NJwAsWgMKTJYsWCxHRswLnaIAML = 34,
		FkUBKThaPaRwfpFcxSvePLaceCZl = 35,
		hgTyGSNrXsceWPdpSnLeplqqpsT = 36,
		XMHoMMmBpsltlmFRkyGyIaozrbG = 37,
		IJSktjcagXfxPxvbmWOPpJRKoyb = 38,
		fZbGGuUiItQsZZkNwnGWhOckJYD = 39,
		xebhynTdxtvoeEzZDYjTCFxdAkV = 40,
		QVlluORWopuQkNHwHaRvXmVcwQA = 41,
		ScHjZoeVvYRbTwoLrfjFCNjtISx = 42
	}
}
