using System;

internal struct AcUaPQzGWdWYaglJmWnskdiCgNK
{
	public IntPtr VhBTBMdAFpqaWuODnxKAnlMulqD;

	public yqIcLiinOcsRJjpdQKrjkkDLiOmY EMusFCwQNzLATJbqytUdqEKEgwBe;

	public bDzedzKrgbdlGWNbpRHVoANyjxi ZtgLWvbHdwlGnBxwNlqnivhPcFO;

	public uint wIykTrinjsQhbVTCExhBhaDOTXq;

	public uint OZXCbzyfeJVptcfXueOFPpFxErd;

	public int ztKWsNWeIoFuebfVObHwbLXELkX;

	public int xpumVntKTYPdUAcEeqwWhsPgirN;

	public int RTwQzyWgdmiDfVtyeEaNgdMceZg;

	internal AcUaPQzGWdWYaglJmWnskdiCgNK(ref lOjRmNhcRhwonUCOQXiLfgRvAbT rawInput)
	{
		VhBTBMdAFpqaWuODnxKAnlMulqD = rawInput.wCEAvStPOQNPByHieIfLAPImqVH.VhBTBMdAFpqaWuODnxKAnlMulqD;
		EMusFCwQNzLATJbqytUdqEKEgwBe = (yqIcLiinOcsRJjpdQKrjkkDLiOmY)rawInput.ygqDlcblBdHdDceQDJzibNhKqWEM.QxDaIeQFcOJvuQfaIwlsuKcvYjM.jMbdrySazXGxqBoUZJERaOtVVTv;
		ZtgLWvbHdwlGnBxwNlqnivhPcFO = (bDzedzKrgbdlGWNbpRHVoANyjxi)rawInput.ygqDlcblBdHdDceQDJzibNhKqWEM.QxDaIeQFcOJvuQfaIwlsuKcvYjM.ODRVxHQvNwoPrwYerTUUUpDuduy.ZtgLWvbHdwlGnBxwNlqnivhPcFO;
		ztKWsNWeIoFuebfVObHwbLXELkX = rawInput.ygqDlcblBdHdDceQDJzibNhKqWEM.QxDaIeQFcOJvuQfaIwlsuKcvYjM.ODRVxHQvNwoPrwYerTUUUpDuduy.vMtUitGkRJfGQBKZpRttUCIWdUX;
		OZXCbzyfeJVptcfXueOFPpFxErd = rawInput.ygqDlcblBdHdDceQDJzibNhKqWEM.QxDaIeQFcOJvuQfaIwlsuKcvYjM.qXpZnucDRGdUXrknbulrmZMMevL;
		xpumVntKTYPdUAcEeqwWhsPgirN = rawInput.ygqDlcblBdHdDceQDJzibNhKqWEM.QxDaIeQFcOJvuQfaIwlsuKcvYjM.QOEzdpOQJoSRCzTmWryIkybVxTg;
		RTwQzyWgdmiDfVtyeEaNgdMceZg = rawInput.ygqDlcblBdHdDceQDJzibNhKqWEM.QxDaIeQFcOJvuQfaIwlsuKcvYjM.nQAAbTUNYOdInEWwObQMjahkyrZ;
		wIykTrinjsQhbVTCExhBhaDOTXq = rawInput.ygqDlcblBdHdDceQDJzibNhKqWEM.QxDaIeQFcOJvuQfaIwlsuKcvYjM.wIykTrinjsQhbVTCExhBhaDOTXq;
	}
}
