using System;

internal struct rqqboATdKanXVBANwiRWmVDCWLd
{
	public IntPtr VhBTBMdAFpqaWuODnxKAnlMulqD;

	public zvemIpuEoAzRNyBIqsNzMAXZEiyJ IlHnqYtYXvFfDNQImyuMmGqvnjE;

	public int XkBIFzMblyArkicoZZuHORPFYZt;

	public pzBCExfDfEahFIZrIkzvfugCKKmO MWQlrEyqpSXqBZrUwsSjzdzsYJe;

	public zqwrcrfPBjjcRqllhxjGsfGYjVOD CNRSmwieXYpSWfaatAFiBTvQUHHq;

	public int wIykTrinjsQhbVTCExhBhaDOTXq;

	internal rqqboATdKanXVBANwiRWmVDCWLd(ref lOjRmNhcRhwonUCOQXiLfgRvAbT rawInput)
	{
		VhBTBMdAFpqaWuODnxKAnlMulqD = rawInput.wCEAvStPOQNPByHieIfLAPImqVH.VhBTBMdAFpqaWuODnxKAnlMulqD;
		IlHnqYtYXvFfDNQImyuMmGqvnjE = (zvemIpuEoAzRNyBIqsNzMAXZEiyJ)rawInput.ygqDlcblBdHdDceQDJzibNhKqWEM.hOKSQsVFahbyPnFtHtuTEPcoMO.UIBrIgNwqkmeDmJrPjlEuknsviE;
		XkBIFzMblyArkicoZZuHORPFYZt = rawInput.ygqDlcblBdHdDceQDJzibNhKqWEM.hOKSQsVFahbyPnFtHtuTEPcoMO.XkBIFzMblyArkicoZZuHORPFYZt;
		MWQlrEyqpSXqBZrUwsSjzdzsYJe = rawInput.ygqDlcblBdHdDceQDJzibNhKqWEM.hOKSQsVFahbyPnFtHtuTEPcoMO.jMbdrySazXGxqBoUZJERaOtVVTv;
		CNRSmwieXYpSWfaatAFiBTvQUHHq = rawInput.ygqDlcblBdHdDceQDJzibNhKqWEM.hOKSQsVFahbyPnFtHtuTEPcoMO.gEOUNiYMqqLAILyJsZDwmOwwBqN;
		wIykTrinjsQhbVTCExhBhaDOTXq = rawInput.ygqDlcblBdHdDceQDJzibNhKqWEM.hOKSQsVFahbyPnFtHtuTEPcoMO.wIykTrinjsQhbVTCExhBhaDOTXq;
	}
}
