[MPRcAuIPIMYWkcRGWUhSVhgfrJj(IxtoKEBdriqLRrkwrCcraCEMJTaE.TiLHwJIqokOMQkbTtUwpdGMvKcC)]
internal struct JUaxdvWVsrrNQvMQGrEBgHKfQTm
{
	[BGPwFQRyVttbjxawAxiynEHOQGP(xTdGZwgiCKEXSLQazMJzOppDnvYm = "a36d02e0-c9f3-11cf-bfc7-444553540000", TETONeGvOFGXjLObsLekbkSPCbkJ = (aROXwdaxgbeVtmneibreFeVBHR.ivCuYLFEFmsbUbmMjKaFcznnbBJ | aROXwdaxgbeVtmneibreFeVBHR.ZVxpXwigRIivluwlxUlCrgyvIVD))]
	internal int xpumVntKTYPdUAcEeqwWhsPgirN;

	[BGPwFQRyVttbjxawAxiynEHOQGP(xTdGZwgiCKEXSLQazMJzOppDnvYm = "a36d02e1-c9f3-11cf-bfc7-444553540000", TETONeGvOFGXjLObsLekbkSPCbkJ = (aROXwdaxgbeVtmneibreFeVBHR.ivCuYLFEFmsbUbmMjKaFcznnbBJ | aROXwdaxgbeVtmneibreFeVBHR.ZVxpXwigRIivluwlxUlCrgyvIVD))]
	internal int RTwQzyWgdmiDfVtyeEaNgdMceZg;

	[BGPwFQRyVttbjxawAxiynEHOQGP(xTdGZwgiCKEXSLQazMJzOppDnvYm = "a36d02e2-c9f3-11cf-bfc7-444553540000", TETONeGvOFGXjLObsLekbkSPCbkJ = (aROXwdaxgbeVtmneibreFeVBHR.myockYRYLQrmPRINWQUDMhEXBNS | aROXwdaxgbeVtmneibreFeVBHR.ivCuYLFEFmsbUbmMjKaFcznnbBJ | aROXwdaxgbeVtmneibreFeVBHR.ZVxpXwigRIivluwlxUlCrgyvIVD))]
	internal int TCogMmKASgopRYQJTNMtdAvdwtIe;

	[BGPwFQRyVttbjxawAxiynEHOQGP(aROXwdaxgbeVtmneibreFeVBHR.ivCuYLFEFmsbUbmMjKaFcznnbBJ | aROXwdaxgbeVtmneibreFeVBHR.OvahfCZCyHKRTDrLpuytesRmOzE)]
	internal byte fGnmRcZnxYWaBWScRujiuMFiNoH;

	[BGPwFQRyVttbjxawAxiynEHOQGP(aROXwdaxgbeVtmneibreFeVBHR.ivCuYLFEFmsbUbmMjKaFcznnbBJ | aROXwdaxgbeVtmneibreFeVBHR.OvahfCZCyHKRTDrLpuytesRmOzE)]
	internal byte dQXOxdABTgJCzwVQWuFfilXySIH;

	[BGPwFQRyVttbjxawAxiynEHOQGP(aROXwdaxgbeVtmneibreFeVBHR.myockYRYLQrmPRINWQUDMhEXBNS | aROXwdaxgbeVtmneibreFeVBHR.ivCuYLFEFmsbUbmMjKaFcznnbBJ | aROXwdaxgbeVtmneibreFeVBHR.OvahfCZCyHKRTDrLpuytesRmOzE)]
	internal byte GgoiaZrFLblePReEgLBjqnzgJlR;

	[BGPwFQRyVttbjxawAxiynEHOQGP(aROXwdaxgbeVtmneibreFeVBHR.myockYRYLQrmPRINWQUDMhEXBNS | aROXwdaxgbeVtmneibreFeVBHR.ivCuYLFEFmsbUbmMjKaFcznnbBJ | aROXwdaxgbeVtmneibreFeVBHR.OvahfCZCyHKRTDrLpuytesRmOzE)]
	internal byte YSSLkGCAZbBxjWuCjhgsUPTNvfJ;

	[BGPwFQRyVttbjxawAxiynEHOQGP(aROXwdaxgbeVtmneibreFeVBHR.myockYRYLQrmPRINWQUDMhEXBNS | aROXwdaxgbeVtmneibreFeVBHR.ivCuYLFEFmsbUbmMjKaFcznnbBJ | aROXwdaxgbeVtmneibreFeVBHR.OvahfCZCyHKRTDrLpuytesRmOzE)]
	internal byte bsUCDbpcwIrLgRfTovZFpJmpQAU;

	[BGPwFQRyVttbjxawAxiynEHOQGP(aROXwdaxgbeVtmneibreFeVBHR.myockYRYLQrmPRINWQUDMhEXBNS | aROXwdaxgbeVtmneibreFeVBHR.ivCuYLFEFmsbUbmMjKaFcznnbBJ | aROXwdaxgbeVtmneibreFeVBHR.OvahfCZCyHKRTDrLpuytesRmOzE)]
	internal byte fXCVOIzZnoQaSJrbPiaiquyVNgT;

	[BGPwFQRyVttbjxawAxiynEHOQGP(aROXwdaxgbeVtmneibreFeVBHR.myockYRYLQrmPRINWQUDMhEXBNS | aROXwdaxgbeVtmneibreFeVBHR.ivCuYLFEFmsbUbmMjKaFcznnbBJ | aROXwdaxgbeVtmneibreFeVBHR.OvahfCZCyHKRTDrLpuytesRmOzE)]
	internal byte hDVFOLkrAsIKtZpxQEFlZPEodIRS;

	[BGPwFQRyVttbjxawAxiynEHOQGP(aROXwdaxgbeVtmneibreFeVBHR.myockYRYLQrmPRINWQUDMhEXBNS | aROXwdaxgbeVtmneibreFeVBHR.ivCuYLFEFmsbUbmMjKaFcznnbBJ | aROXwdaxgbeVtmneibreFeVBHR.OvahfCZCyHKRTDrLpuytesRmOzE)]
	internal byte AZDcnGNAwLJTHLRwvBKOSaJbGmG;
}
